# ワークフローの名前
name: Lint Check

# このワークフローが実行されるタイミングを指定
on:
  # mainブランチへのpush時
  push:
    branches: ["main"]
  # mainブランチへのプルリクエスト作成・更新時
  pull_request:
    branches: ["main"]

# 実行するジョブを定義
jobs:
  lint:
    # ジョブの名前
    name: Run ESLint
    # 実行する仮想環境の種類
    runs-on: ubuntu-latest

    # ジョブのステップを定義
    steps:
      # 1. リポジトリのコードをチェックアウトする
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Node.js環境をセットアップする
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # プロジェクトで使用しているNode.jsのバージョンを指定
          node-version: "20"
          # pnpmのキャッシュを有効にし、インストールを高速化
          cache: "pnpm"

      # 3. 依存パッケージをインストールする
      - name: Install Dependencies
        run: pnpm ci

      # 4. TypeScriptの型チェックを実行する
      - name: Type Check
        run: pnpm tsc --noEmit

      # 5. Lintチェックを実行する
      - name: Run Lint
        run: pnpm lint
