name: Format Check

on:
  pull_request:
    branches: ["main"]

jobs:
  prettier:
    name: Run Prettier Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm ci

      # Prettierがインストールされているかチェック
      - name: Check if Prettier is installed
        id: check-prettier
        run: |
          if pnpm list prettier > /dev/null 2>&1; then
            echo "prettier-installed=true" >> $GITHUB_OUTPUT
          else
            echo "prettier-installed=false" >> $GITHUB_OUTPUT
          fi

      # Prettierがインストールされている場合のみ実行
      - name: Check Formatting
        if: steps.check-prettier.outputs.prettier-installed == 'true'
        run: pnpm prettier --check .

      # Prettierがインストールされていない場合はスキップ
      - name: Skip Prettier Check
        if: steps.check-prettier.outputs.prettier-installed == 'false'
        run: echo "Prettier is not installed. Skipping format check."
