name: Run Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm ci

      # テストスクリプトが存在するかチェック
      - name: Check if test script exists
        id: check-test
        run: |
          if pnpm run --silent test > /dev/null 2>&1; then
            echo "test-script-exists=true" >> $GITHUB_OUTPUT
          else
            echo "test-script-exists=false" >> $GITHUB_OUTPUT
          fi

      # テストスクリプトが存在する場合のみ実行
      - name: Run Tests
        if: steps.check-test.outputs.test-script-exists == 'true'
        run: pnpm test

      # テストスクリプトが存在しない場合はスキップ
      - name: Skip Tests
        if: steps.check-test.outputs.test-script-exists == 'false'
        run: echo "No test script found. Skipping tests."
